# Generated by Django 4.1.2 on 2022-10-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JaySong',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cid', models.CharField(max_length=64)),
                ('song_info', models.TextField()),
                ('flac_url', models.TextField()),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jay_song',
            },
        ),
    ]
