# Generated by Django 4.1.2 on 2022-10-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyTasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cy_tasks',
            },
        ),
    ]
