# Generated by Django 4.1.2 on 2022-10-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pers', '0002_cytasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='cytasks',
            name='task_id',
            field=models.CharField(default='', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
